name: Assign reviewers based on assignees
on:
  pull_request:
    types: [assigned, unassigned]
    

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        if: startsWith(github.event.pull_request.title, 'chore(deps):')
        run: echo "Pull request was created by Renovate automatically."
  assignee_to_reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Assignee to Reviewer
        uses: pullreminders/assignee-to-reviewer-action@v1.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
